# Generated by Django 4.0.3 on 2022-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetime',
            name='note',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
