# Generated by Django 4.0.3 on 2022-05-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_recipetime_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetime',
            name='time_type',
            field=models.CharField(choices=[('Additional', 'Additional'), ('Cook', 'Cook'), ('Preparation', 'Preparation'), ('Total', 'Total')], max_length=20),
        ),
    ]
