# Generated by Django 4.0.3 on 2022-05-20 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_recipetime_time_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
