# Generated by Django 4.0.3 on 2022-05-25 15:59

from django.db import migrations


def set_recipetag_user(apps, schema_editor):
    RecipeTag = apps.get_model("main", "RecipeTag")
    for recipe_tag in RecipeTag.objects.all():
        recipe_tag.user_id = recipe_tag.recipe.user_id
        recipe_tag.save()


def unset_recipetag_user(apps, shcema_editor):
    RecipeTag = apps.get_model("main", "RecipeTag")
    for recipe_tag in RecipeTag.objects.all():
        recipe_tag.user_id = None
        recipe_tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_recipetag_user"),
    ]

    operations = [migrations.RunPython(set_recipetag_user, unset_recipetag_user)]
