# Generated by Django 4.0.3 on 2022-05-25 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_recipetag_set_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
