# Generated by Django 4.0.3 on 2022-05-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_recipetag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipetag',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_tags',
            field=models.ManyToManyField(related_name='recipes', to='main.recipetag'),
        ),
    ]
