# Generated by Django 4.0.3 on 2022-06-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_recipetag_recipe_recipe_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
