# Generated by Django 4.0.6 on 2022-07-14 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_recipe_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('description', 'user')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_equipment',
            field=models.ManyToManyField(related_name='recipes', to='main.recipeequipment'),
        ),
    ]
