# Generated by Django 4.0.6 on 2022-07-21 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_recipeequipment_recipe_recipe_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_brand',
            field=models.ManyToManyField(related_name='recipes', to='main.recipebrand'),
        ),
    ]
