# Generated by Django 4.0.2 on 2022-03-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recipetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetime',
            name='time_type',
            field=models.CharField(choices=[('Additional', 'Additional'), ('Cook', 'Cook'), ('Preparation', 'Preparation')], max_length=20),
        ),
    ]
