# Generated by Django 4.0.2 on 2022-03-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_recipetime_time_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='category',
            new_name='token_type',
        ),
    ]
